// <auto-generated />
using System;
using Giorgione.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Giorgione.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241118190113_GuildBirthdayChannelId")]
    partial class GuildBirthdayChannelId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Giorgione.Data.Models.Guild", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("id");

                    b.Property<long?>("AnimeFeedChannelId")
                        .HasColumnType("bigint")
                        .HasColumnName("anime_feed_channel_id");

                    b.Property<decimal?>("BirthdayChannelId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("birthday_channel_id");

                    b.Property<long?>("StarboardId")
                        .HasColumnType("bigint")
                        .HasColumnName("starboard_id");

                    b.HasKey("Id")
                        .HasName("pk_guilds");

                    b.ToTable("guilds", (string)null);
                });

            modelBuilder.Entity("Giorgione.Data.Models.Member", b =>
                {
                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("user_id");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("guild_id");

                    b.Property<bool>("DisplayBirthday")
                        .HasColumnType("boolean")
                        .HasColumnName("display_birthday");

                    b.HasKey("UserId", "GuildId")
                        .HasName("pk_members");

                    b.HasIndex("GuildId")
                        .HasDatabaseName("ix_members_guild_id");

                    b.ToTable("members", (string)null);
                });

            modelBuilder.Entity("Giorgione.Data.Models.SeenEpisode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("Id")
                        .HasName("pk_seen_episodes");

                    b.ToTable("seen_episodes", (string)null);
                });

            modelBuilder.Entity("Giorgione.Data.Models.User", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("BirthdayRepresentation")
                        .HasColumnType("date")
                        .HasColumnName("birthday");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Giorgione.Data.Models.Member", b =>
                {
                    b.HasOne("Giorgione.Data.Models.Guild", "Guild")
                        .WithMany("Members")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_members_guilds_guild_id");

                    b.HasOne("Giorgione.Data.Models.User", "User")
                        .WithMany("GuildSettings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_members_users_user_id");

                    b.Navigation("Guild");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Giorgione.Data.Models.Guild", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("Giorgione.Data.Models.User", b =>
                {
                    b.Navigation("GuildSettings");
                });
#pragma warning restore 612, 618
        }
    }
}
